# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('goodsType', models.CharField(max_length=20)),
                ('conditionGoods', models.CharField(max_length=20)),
                ('imagesGoods', models.ImageField(upload_to='images')),
                ('datePostGoods', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
