# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='description',
            new_name='descriptionGoods',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='nameGoods',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goodsType',
            new_name='typeGoods',
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagesGoods',
            field=models.ImageField(upload_to='path/images'),
        ),
    ]
