# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import webAdmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('webAdmin', '0002_auto_20190824_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='priceGoods',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagesGoods',
            field=models.ImageField(upload_to=webAdmin.models.Goods.upload_path_handler),
        ),
    ]
