# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAdmin', '0003_auto_20190825_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='rateGoods',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
