# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAdmin', '0007_goods_imagesgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='imagesGoods',
            field=models.ImageField(upload_to='gambar'),
        ),
    ]
