# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-04 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAdmin', '0009_auto_20190903_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='slugifyGoods',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
